<?php

/**
 * Implements hook_entity_info().
 */
function en2cn_user_entity_info() {
  $return['en2cn_user'] = array(
    'label' => t('en2cn User'),
    'controller class' => 'En2CnUserController',
    'base table' => 'en2cn_user',
    'uri callback' => 'en2cn_user_uri',
    'static cache' => TRUE,
    'field cache' => FALSE,
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'uid',
     ),
  );

  return $return;
}

/**
 * Entity uri callback.
 */
function en2cn_user_uri($user) {
  return array(
    'path' => 'user/' . $user->uid,
  );
}

/**
 * Implements hook_user_insert().
 */
function en2cn_user_user_insert(&$edit, $account, $category) {
  entity_get_controller('en2cn_user')->insert($account);
}

/**
 * Implements hook_user_insert().
 */
function en2cn_user_user_delete($account) {
  entity_get_controller('en2cn_user')->delete($account);
}