<?php

/**
 * Implements hook_entity_info().
 */
function en2cn_user_entity_info() {
  $return['en2cn_user'] = array(
    'label' => t('en2cn User'),
    'controller class' => 'En2CnUserController',
    'base table' => 'en2cn_user',
    'uri callback' => 'en2cn_user_uri',
    'static cache' => TRUE,
    'field cache' => FALSE,
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'uid',
     ),
  );

  return $return;
}

/**
 * Entity uri callback.
 */
function en2cn_user_uri($user) {
  return array(
    'path' => 'user/' . $user->uid,
  );
}

/**
 * Implements hook_user_insert().
 */
function en2cn_user_user_insert(&$edit, $account, $category) {
  entity_get_controller('en2cn_user')->insert($account);
}

/**
 * Implements hook_user_insert().
 */
function en2cn_user_user_delete($account) {
  entity_get_controller('en2cn_user')->delete($account);
}

/**
 * Implements hook_help().
 */
function en2cn_user_help($path, $arg) {
  if ($path == 'admin/help#en2cn_user') {
    return t('User module of en2cn project for adding additional user
    information fields needed.');
  }
}

/**
 * Implements hook_block_info().
 */
function en2cn_user_block_info() {
  $blocks = array();

  $blocks['user_profile_summary'] = array(
    'info' => t('A listing of important user profile entries.'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function en2cn_user_block_view($delta = '') {
  if ($delta == 'user_profile_summary') {
    if (user_is_logged_in()) {
      global $user;
      $login_user = user_load($user->uid);

      $user_summary = array();
      $user_summary[] = t('Joined: ') . format_date($login_user->created);
      $user_summary[]  = t('Timezone: ') . $login_user->timezone;
      $user_summary[] = t('Points: ') . en2cn_user_get_points($user->uid);

      $theme_args = array('items' => $user_summary, 'type' => 'ul');
      $content = theme('item_list', $theme_args);

      $block = array(
        'subject' => $login_user->name,
        'content' => $content,
      );
    } else {
      $block = array(
        'subject' => 'Config needed',
        'content' => 'This block should not be displayed when the user
        does not login. It can be configured at Admin->Block->Config.',
      );
    }

    return $block;
  }
}

/**
 * Get a en2cn user's contribution points
 * @param $uid
 * @return mixed
 */
function en2cn_user_get_points($uid) {
  return entity_get_controller('en2cn_user')->getPoints($uid);
}
